apiVersion: v1
kind: Service
metadata:
  name: auth-edge-service
  labels:
    app: auth-edge-service
    app.kubernetes.io/name: auth-edge-service
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: auth-platform
spec:
  type: ClusterIP
  selector:
    app: auth-edge-service
  ports:
    - name: grpc
      port: 8080
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
