apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
  - auth-edge-service/
  - token-service/
  - session-identity-core/
  - iam-policy-service/
  - mfa-service/
  - cache-service/

commonLabels:
  app.kubernetes.io/part-of: auth-platform
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: auth-platform-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
