---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-edge-service
  namespace: auth-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-service
  namespace: auth-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-identity-core
  namespace: auth-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-policy-service
  namespace: auth-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mfa-service
  namespace: auth-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-service
  namespace: auth-system
automountServiceAccountToken: false
