apiVersion: v1
kind: Service
metadata:
  name: session-identity-core
  labels:
    app: session-identity-core
    app.kubernetes.io/name: session-identity-core
    app.kubernetes.io/part-of: auth-platform
spec:
  type: ClusterIP
  selector:
    app: session-identity-core
  ports:
    - name: http
      port: 4000
      targetPort: http
    - name: grpc
      port: 8082
      targetPort: grpc
    - name: metrics
      port: 9092
      targetPort: metrics
