apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: password-recovery

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - resiliencepolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: auth-platform
  app.kubernetes.io/managed-by: kustomize
